// <auto-generated />
namespace Proyecto_final.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class tablas2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tablas2));
        
        string IMigrationMetadata.Id
        {
            get { return "201511200639434_tablas2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
